version: '2'
services:
  ace_data:
    image: chooban/ace-data-container:latest
  previewsapi:
    image: chooban/ace-previews-api:latest
    depends_on:
      - ace_data
    volumes_from:
      - ace_data:ro
    ports:
      - 8100
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=debug
  site:
    build: .
    ports:
      - 8080:3001
    volumes:
      - .:/opt/apps/previews-charts
